/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCheckRouteImport } from './routes/app/check'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronPhotoRetentionRouteImport } from './routes/api/cron/photo-retention'
import { Route as ApiCronRecheckRouteImport } from './routes/api/cron/recheck'
import { Route as AppChecksCheckIdRouteImport } from './routes/app/checks.$checkId'
import { Route as AppListingListingIdRouteImport } from './routes/app/listing.$listingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckRoute = AppCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPhotoRetentionRoute = ApiCronPhotoRetentionRouteImport.update({
  id: '/api/cron/photo-retention',
  path: '/api/cron/photo-retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRecheckRoute = ApiCronRecheckRouteImport.update({
  id: '/api/cron/recheck',
  path: '/api/cron/recheck',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChecksCheckIdRoute = AppChecksCheckIdRouteImport.update({
  id: '/checks/$checkId',
  path: '/checks/$checkId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListingListingIdRoute = AppListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/check': typeof AppCheckRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/photo-retention': typeof ApiCronPhotoRetentionRoute
  '/api/cron/recheck': typeof ApiCronRecheckRoute
  '/app/checks/$checkId': typeof AppChecksCheckIdRoute
  '/app/listing/$listingId': typeof AppListingListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/check': typeof AppCheckRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/photo-retention': typeof ApiCronPhotoRetentionRoute
  '/api/cron/recheck': typeof ApiCronRecheckRoute
  '/app/checks/$checkId': typeof AppChecksCheckIdRoute
  '/app/listing/$listingId': typeof AppListingListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/check': typeof AppCheckRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/photo-retention': typeof ApiCronPhotoRetentionRoute
  '/api/cron/recheck': typeof ApiCronRecheckRoute
  '/app/checks/$checkId': typeof AppChecksCheckIdRoute
  '/app/listing/$listingId': typeof AppListingListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/landing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/app/check'
    | '/app/'
    | '/api/auth/$'
    | '/api/cron/photo-retention'
    | '/api/cron/recheck'
    | '/app/checks/$checkId'
    | '/app/listing/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/app/check'
    | '/app'
    | '/api/auth/$'
    | '/api/cron/photo-retention'
    | '/api/cron/recheck'
    | '/app/checks/$checkId'
    | '/app/listing/$listingId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/landing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/app/check'
    | '/app/'
    | '/api/auth/$'
    | '/api/cron/photo-retention'
    | '/api/cron/recheck'
    | '/app/checks/$checkId'
    | '/app/listing/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPhotoRetentionRoute: typeof ApiCronPhotoRetentionRoute
  ApiCronRecheckRoute: typeof ApiCronRecheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/check': {
      id: '/app/check'
      path: '/check'
      fullPath: '/app/check'
      preLoaderRoute: typeof AppCheckRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/photo-retention': {
      id: '/api/cron/photo-retention'
      path: '/api/cron/photo-retention'
      fullPath: '/api/cron/photo-retention'
      preLoaderRoute: typeof ApiCronPhotoRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/recheck': {
      id: '/api/cron/recheck'
      path: '/api/cron/recheck'
      fullPath: '/api/cron/recheck'
      preLoaderRoute: typeof ApiCronRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/checks/$checkId': {
      id: '/app/checks/$checkId'
      path: '/checks/$checkId'
      fullPath: '/app/checks/$checkId'
      preLoaderRoute: typeof AppChecksCheckIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/listing/$listingId': {
      id: '/app/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/app/listing/$listingId'
      preLoaderRoute: typeof AppListingListingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCheckRoute: typeof AppCheckRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChecksCheckIdRoute: typeof AppChecksCheckIdRoute
  AppListingListingIdRoute: typeof AppListingListingIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCheckRoute: AppCheckRoute,
  AppIndexRoute: AppIndexRoute,
  AppChecksCheckIdRoute: AppChecksCheckIdRoute,
  AppListingListingIdRoute: AppListingListingIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LandingRoute: LandingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPhotoRetentionRoute: ApiCronPhotoRetentionRoute,
  ApiCronRecheckRoute: ApiCronRecheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
